### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by willthetanman** [fedora-infra/flask-oidc#15]
It seems like another error is being raised that wasn't present in 1.4.0, it isn't as obvious what is causing this 

```[2023-08-22 18:44:23 +0000] [10] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 354, in handle_request
    util.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 641, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_oidc/views.py", line 52, in login_view
    return g._oidc_auth.authorize_redirect(redirect_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/flask_client/apps.py", line 43, in authorize_redirect
    rv = self.create_authorization_url(redirect_uri, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/base_client/sync_app.py", line 309, in create_authorization_url
    metadata = self.load_server_metadata()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/authlib/integrations/base_client/sync_app.py", line 295, in load_server_metadata
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://dev-530876.okta.com/oauth2/.well-known/openid-configuration


Sample of my client_secrets:

```{
  "web": {
    "client_id": "0oa3fm12fsfJWRO294x7",
    "client_secret": "[redacted]",
    "auth_uri": "https://dev-530876.okta.com/oauth2/v1/authorize",
    "token_uri": "https://dev-530876.okta.com/oauth2/v1/token",
    "issuer": "https://dev-530876.okta.com/oauth2/"
  }
}

**Comment by willthetanman** [comment]
Could be related but there is an extra "next" parameter added to the URL, this could be causing issues but not sure

```https://localhost:5000/login?next=https%3A%2F%2Flocalhost%3A5000%2F

**Comment by abompard** [comment]
Hey! This is because the OpenID metadata is not where flask-oidc looks for it at the moment, you could fix that by changing the `issuer` in your `client_secrets` and removing the last `oauth2/` part (the metadata is at https://dev-530876.okta.com/.well-known/openid-configuration).
Did you get your `client_secrets` by running `oidc-register`?

**Comment by willthetanman** [comment]
Removing `oauth2/` from my `issuer` introduced a new error even though I have `OIDC_USER_INFO_ENABLED` set to `True`

```Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/app/multicloud/routes.py", line 52, in before_request
    info = oidc.user_getinfo(["preferred_username", "email", "sub", "name"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_oidc/__init__.py", line 229, in user_getinfo
    raise RuntimeError(
RuntimeError: User info is disabled in configuration (OIDC_USER_INFO_ENABLED)
```
I did not get my `client_secrets` from `oidc-register` these were manually created.

Would flask-oidc eventually support having `oauth2/` in the issuer like in `1.4.0`?

**Comment by abompard** [comment]
> Removing `oauth2/` from my `issuer` introduced a new error even though I have `OIDC_USER_INFO_ENABLED` set to `True`

Yeah, I'm now realizing that there's one piece of information that I require to have in the `client_secrets` file, but I don't actually use. I'll fix that.

> Would flask-oidc eventually support having `oauth2/` in the issuer like in `1.4.0`?

Probably not, as the issuer value is actually incorrect, but versions <2.0.0 were ignoring it. Our backend library now wants a valid value.

**Comment by willthetanman** [comment]
Thank you for the patches, I have tested `2.0.2` and everything is working as before, this was very informative. Much appreciated.
