### ISSUE TITLE
module 'importlib' has no attribute 'metadata'

### ISSUE THREAD

**Issue by fortunso** [fedora-infra/flask-oidc#65]
After authlib update to version 1.3.0 this error is showing up:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
    
  File "/usr/local/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
    
  File "/task/api.py", line 23, in <module>
    from flask_oidc import OpenIDConnect
    
  File "/usr/local/lib/python3.8/site-packages/flask_oidc/__init__.py", line 16, in <module>
    from authlib.integrations.flask_oauth2 import ResourceProtector
    
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/flask_oauth2/__init__.py", line 4, in <module>
    from .resource_protector import (
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/flask_oauth2/resource_protector.py", line 15, in <module>
  
    from .errors import raise_http_exception
  File "/usr/local/lib/python3.8/site-packages/authlib/integrations/flask_oauth2/errors.py", line 6, in <module>
    _version = importlib.metadata.version('werkzeug').split('.')[0]
    
AttributeError: module 'importlib' has no attribute 'metadata'
````

**Comment by willscavforlabkeys** [comment]
+1 Just ran into the same error.

**Comment by abompard** [comment]
This error comes from authlib, please open a ticket with them. I would first try to update the authlib version to the latest available, to make sure they didn't fix it in between.
